locations = { "UK": ["London", "England", "Manchester", "United Kingdom", "Glasgow", "Essex", "Liverpool", "Leeds"],
  "Spain": ["Barcelona", "Madrid", "Espaa", "Camp Nou", "Barcelona"],
  "Indonesia": ["Jakarta", "Jakarta, Indonesia"],
  "Venezuela": [],
  "Mexico": ["Mxico"],
  "India": ["Bombay", "Mumbai", "New Delhi"],
  "El Salvador": [],
  "Guatemala": [],
  "Colombia": ["Bogot, Colombia"],
  "Nigeria": ["Lagos"],
  "USA": ["New York", "Los Angeles", "Los Angeles, CA", "United States", "Miami, FL", "Miami", "California", "Chicago", "NYC"],
  "South Africa": ["Johannesburg", "Cape Town"],
  "Panama": ["Panam"],
  "Canada": ["Toronto"],
  "International": ["Worldwide", "Earth"],
  "Puerto Rico": [],
  "Argentina": ["Buenos Aires"],
  "Ireland": [],
  "Pakistan": ["Sialkot"],
  "UAE": ["Dubai"],
  "France": ["Paris"],
  "Poland": [],
  "Kenya" : ["Nairobi"],
  "Costa Rica": [],
  "Denmark": [],
  "Sweden": [],
  "Brazil": ["Brasil"],
  "Egypt": ["Cairo"],
  "Qatar": ["Doha"]
}
